name = "my-edge-tunnel"
main = "_worker.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "mm3.ttsm.gv.uy"
custom_domain = true

[vars]
UUID = "56b1cbec-9519-4ead-9643-05f240a92107"
PROXYIP = "104.16.148.1"
