name = "my-edge-tunnel"
main = "_worker.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "mm.ttsm.eu.cc"
custom_domain = true

[vars]
UUID = "56b1cbec-9519-4ead-9643-05f240a92107"
PROXYIP = "cdn.anycast.eu.org"
